language: elixir
elixir: '1.7.3'
otp_release: '21.3'
environment:
  - MIX_ENV=test

before_script:
  - kerl update releases

script:
  - mix test && ( [[ -n "$LEGACY_ELIXIR" ]] || mix credo )

matrix:
  include:
    - elixir: '1.3'
      otp_release: '18.3'
      env: MIX_ENV=test LEGACY_ELIXIR=1

    - elixir: '1.4'
      otp_release: '19.3'
      env: MIX_ENV=test MIX_EXS=$TRAVIS_BUILD_DIR/mix.exs.pre1.7

    - elixir: '1.5'
      otp_release: '19.3'
      env: MIX_ENV=test MIX_EXS=$TRAVIS_BUILD_DIR/mix.exs.pre1.7

    - elixir: '1.5'
      otp_release: '20.0'
      env: MIX_ENV=test MIX_EXS=$TRAVIS_BUILD_DIR/mix.exs.pre1.7

    - elixir: '1.6'
      otp_release: '20.0'
      env: MIX_ENV=test MIX_EXS=$TRAVIS_BUILD_DIR/mix.exs.pre1.7

    - elixir: '1.6'
      otp_release: '21.1'
      env: MIX_ENV=test MIX_EXS=$TRAVIS_BUILD_DIR/mix.exs.pre1.7

    - elixir: '1.7'
      otp_release: '20.0'

    - elixir: '1.8'
      otp_release: '20.0'

    - elixir: '1.8'
      otp_release: '21.0'

    - elixir: '1.9'
      otp_release: '21.0'

    - elixir: '1.9'
      otp_release: '22.0'
